### ISSUE TITLE
Lack of template issues

### ISSUE THREAD

**Issue by RunAwayDSP** [Demiurge-DSP/demiurge-website#3]
With the lack of template each page index/faq/Operating-Costs etc will have overlapping code 

I suggest adding `<head>` code to another 
```html
			<!-- start of head section -->
				<!--#include virtual="head.html" -->
			<!-- end of head section -->
```

I would also consider adding the DIV id's to their respective .html file

Another possible suggestion is to use variable content div 
instead of index.html and faq.html
use index.php?content=faq

**Comment by TeoTwawki** [comment]
> use index.php?content=faq

This was close to the original intent, but I never got to it. much of the mess is me just going off onto other things and doing leaving things unfinished. Originally I'd have dynamically transcluded content form those pages into a variable content div so that we could still edit them as if they were individual pages. I wanted the status stuff at top and the navigation stuff at left to just be universal so content from whatever would be loaded to that middle area. There is some completely unused space reserved for things I canceled/removed too.

**Comment by TeoTwawki** [comment]
The department of redundancy department experienced severe cutbacks today.
